export const MENUITYINDEXSTATE = 'MENUITYINDEXSTATE'

export const COMMUNITYINDEXSTATE = 'COMMUNITYINDEXSTATE'

export const SHOPINDEXSTATE = 'SHOPINDEXSTATE'

export const SETLISTTITLE = 'SETLISTTITLE'

export const SETFOOTSTATE = 'SETFOOTSTATE'
